config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :books do
    post 'add_to_favorites', on: :member
    post 'remove_favorites', on: :member
    get 'favorites', on: :collection
  end
  resources :authors
  resources :publishers
  get 'dashboard', to: 'dashboard#dashboard'
  post 'dashboard/update_book_prices', to: 'dashboard#update_book_prices'
  get 'dashboard/books', to: 'dashboard#books'

  namespace :api do
    resources :books, only: %i[index show create update destroy]
  end

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authorize_admin
  before_action :set_book, only: [:show, :edit, :update, :destroy]


  def dashboard
  end

  def books
    if params[:query].present?
      @books = Book.search_by_title_and_author_and_publisher(params[:query])
    else
      @books = Book.all
    end
  end

  def update_book_prices
    publisher_id = params[:book_price_update][:publisher_id].to_i
    action = params[:book_price_update][:action]
    percentage = params[:book_price_update][:percentage].to_f

    PriceUpdateJob.perform_later(publisher_id, action, percentage)

    flash[:notice] = 'Book price has been updated.'
    redirect_to dashboard_path
  end
end

app/views/dashboard/books.html.erb
<div class="container">
  <h1>Books</h1>
  <%= link_to 'Back to dashboard', dashboard_path %>
  <%= link_to 'New Book', new_book_path %>
    <div class="container">
      <div class="container">
        <%= form_with url: dashboard_books_path, method: :get, html: {class: 'm-4 d-flex gap-3' } do |f| %>
          <%= f.text_field :query,
                            class: "form-control",
                            placeholder: 'Search for a Book',
                            value: params[:query]
                            %>
          <%= f.submit "Search", class: "btn btn-flat" %>
          <% end %>
      </div>
  </div>
  <table class="border">
    <thead>
      <tr>
        <th>Title</th>
        <th>ISBN</th>
        <th>Date of Publication</th>
        <th>Review</th>
        <th>Price</th>
        <th>Publisher</th>
        <th>Author</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.isbn %></td>
          <td><%= book.date_of_publication %></td>
          <td><%= book.review %></td>
          <td><%= book.price %></td>
          <td><%= book.publisher.name %></td>
          <td><%= book.author.first_name %> <%= book.author.last_name %> (Age: <%= Time.now.year - book.author.date_of_birth.year %>)</td>
          <td>
            <%= link_to 'Show', book %>
            <%= link_to 'Edit', edit_book_path(book) %>
            <%= button_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?'} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dashboard/dashboard.html.erb
<h1 class="text-center mt-4">Welcome to the Admin Dashboard!</h1>
<div class="container mt-5">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="card">
          <div class="card-header">Books</div>
          <div class="card-body">
            <h5 class="card-title">Manage books</h5>
            <p class="card-text">Add, edit, and delete books.</p>
            <%= link_to "Manage Books", dashboard_books_path, class: "btn btn-flat" %>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card">
          <div class="card-header">Authors</div>
          <div class="card-body">
            <h5 class="card-title">Manage Authors</h5>
            <p class="card-text">Add, edit, and delete Authors.</p>
            <%= link_to "Manage Authors", authors_path, class: "btn btn-flat" %>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card">
          <div class="card-header">Publishers</div>
          <div class="card-body">
            <h5 class="card-title">Manage Publishers</h5>
            <p class="card-text">Add, edit, and delete Publishers.</p>
            <%= link_to "Manage Publishers", publishers_path, class: "btn btn-flat" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row mt-4 justify-content-center align-items-center mt-5">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">Update Book Prices</div>
        <div class="card-body">
          <h5 class="card-title">Update book prices for a publisher</h5>
          <p class="card-text">
            Select a publisher, choose an action, and enter a percentage.
          </p>
            <%= simple_form_for :book_price_update, url: dashboard_update_book_prices_path, method: :post do |f| %>
              <div class="form-group">
                <%= f.label :publisher_id, 'Select Publisher' %>
                <%= f.select :publisher_id, options_for_select(Publisher.all.map { |p| [p.name, p.id] }), { prompt: 'Select a Publisher' }, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :action, 'Select Action' %>
                <%= f.select :action, [['Increase', 'increase'], ['Decrease', 'decrease']], { prompt: 'Select an Action' }, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.input :percentage, step: 0.01, class: 'form-control' %>
              </div>
              <%= f.submit 'Update Prices', class: 'btn btn-flat' %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>