config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :books do
    post 'add_to_favorites', on: :member
    post 'remove_favorites', on: :member
    get 'favorites', on: :collection
  end
  resources :authors
  resources :publishers
  get 'dashboard', to: 'dashboard#dashboard'
  post 'dashboard/update_book_prices', to: 'dashboard#update_book_prices'
  get 'dashboard/books', to: 'dashboard#books'

  namespace :api do
    resources :books, only: %i[index show create update destroy]
  end

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy

  include PgSearch::Model

  pg_search_scope :search_author,
  against: [ :first_name, :last_name, :date_of_birth, :nationality, :about  ],
  using: {
    tsearch: { prefix: true }
  }

  # Validations
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :date_of_birth, presence: true
  validates :about, presence: true
  validates :nationality, presence: true
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authorize_admin
  before_action :set_author, only: %i[ show edit update destroy ]

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    @author.save
    redirect_to authors_path
  end

  def show
  end

  def index
    if params[:query].present?
      @authors = Author.search_author(params[:query])
    else
      @authors = Author.all
    end
  end

  def edit
  end

  def update
    @author.update(author_params)
    redirect_to authors_path
  end

  def destroy
    @author.destroy
    redirect_to authors_path
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:first_name, :last_name, :date_of_birth, :about, :nationality)
  end
end

app/views/authors/edit.html.erb
<div class="container">
  <h3>Edit <%= "#{@author.first_name} #{@author.last_name}" %></h3>
  <div class="row justify-content-center">
    <div class="col-6">
      <%= simple_form_for(@author) do |f| %>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :date_of_birth %>
        <%= f.input :about %>
        <%= f.input :nationality %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/authors/index.html.erb
<div class="container">
  <h1>Authors</h1>
  <%= link_to 'Back to dashboard', dashboard_path %>
  <%= link_to 'New Author', new_author_path %>
  <div class="container">
    <div class="container">
      <%= form_with url: authors_path, method: :get, html: {class: 'm-4 d-flex gap-3' } do |f| %>
        <%= f.text_field :query,
                          class: "form-control",
                          placeholder: 'Search for an author',
                          value: params[:query]
                          %>
        <%= f.submit "Search", class: "btn btn-flat" %>
        <% end %>
  </div>
</div>
  <table class="border">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Date of Birth</th>
        <th>About</th>
        <th>Nationality</th>
        <th>Book Count</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @authors.each do |author| %>
        <tr>
          <td><%= author.first_name %></td>
          <td><%= author.last_name %></td>
          <td><%= author.date_of_birth %></td>
          <td><%= author.about %></td>
          <td><%= author.nationality %></td>
          <td><%= link_to author.books.count, author_path(author) %></td>
          <td>
            <%= link_to 'Show', author %>
            <%= link_to 'Edit', edit_author_path(author) %>
            <%= button_to 'Delete', author, method: :delete, data: { confirm: 'Are you sure?'} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/authors/new.html.erb
<h1>Create new author</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6 mb-3">
      <%= simple_form_for(@author) do |f| %>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :date_of_birth %>
        <%= f.input :about %>
        <%= f.input :nationality %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/authors/show.html.erb
<div class="container">
  <div class="container-show">
    <h1>Details for Author id: <%= @author.id %></h1>
    <div class="item-details">
        <p><strong>First Name:</strong> <%= @author.first_name %></p>
        <p><strong>Last Name:</strong> <%= @author.last_name %></p>
        <p><strong>Date of Birth:</strong> <%= @author.date_of_birth %></p>
        <p><strong>About:</strong> <%= @author.about %></p>
        <p><strong>Nationality:</strong> <%= @author.nationality %></p>
    </div>
    <a class="btn btn-flat" href="<%= authors_path %>">Back to List</a>
  </div>
</div>
<div class="d-flex flex-wrap gap-4 justify-content-center mb-5">
  <% @author.books.each do |book| %>
    <div class="d-flex card text-center col-sm-1 col-md-3">
      <div class="card-header">
        Author: <%= "#{book.author.first_name} #{book.author.last_name}" %>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= book.title %></h5>
        <p class="card-text">Published by: <%= book.publisher.name %></p>
        <p>Price $<%= book.price %></p>
        <% if user_signed_in? %>
          <%= button_to "Add to Favorites", add_to_favorites_book_path(book), method: :post, class: "btn btn-flat", remote: true, data: { confirm: 'Book added to favorites. View your favorites now?' } %>
        <% else %>
          <%= button_to "Log in to add to Favorites", new_user_session_path, class: "btn btn-flat" %>
        <% end %>
      </div>
      <div class="card-footer text-muted d-flex justify-content-center align-items-center">
        Rating: <% book.review.times do %>
          <i class="fa-solid fa-star text-warning"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>