config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :books do
    post 'add_to_favorites', on: :member
    post 'remove_favorites', on: :member
    get 'favorites', on: :collection
  end
  resources :authors
  resources :publishers
  get 'dashboard', to: 'dashboard#dashboard'
  post 'dashboard/update_book_prices', to: 'dashboard#update_book_prices'
  get 'dashboard/books', to: 'dashboard#books'

  namespace :api do
    resources :books, only: %i[index show create update destroy]
  end

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books

  include PgSearch::Model

  pg_search_scope :search_publisher,
  against: [ :name ],
  using: {
    tsearch: { prefix: true }
  }

  # Validations
  validates :name, presence: true
  validates :name, length: { minimum: 2 }
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :authorize_admin
  before_action :set_publisher, only: [:show, :edit, :update, :destroy]

  def new
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    @publisher.save
    redirect_to publishers_path
  end

  def show
    @book_count = Book.where(publisher_id: @publisher.id).count
  end

  def index
    if params[:query].present?
      @publishers = Publisher.search_publisher(params[:query])
    else
      @publishers = Publisher.all
    end
  end

  def edit
  end

  def update
    @publisher.update(publisher_params)
    redirect_to publishers_path
  end

  def destroy
    @publisher.destroy
    redirect_to publishers_path
  end

  private

  def set_publisher
    @publisher = Publisher.find(params[:id])
  end

  def publisher_params
    params.require(:publisher).permit(:name)
  end
end

app/views/publishers/edit.html.erb
<div class="container">
  <h3>Edit <%= @publisher.name %></h3>
  <div class="row justify-content-center">
    <div class="col-6">
      <%= simple_form_for(@publisher) do |f| %>
        <%= f.input :name %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/publishers/index.html.erb
<div class="container">
  <h1>Publishers</h1>
  <%= link_to 'Back to dashboard', dashboard_path %>
  <%= link_to 'New Publisher', new_publisher_path %>
    <div class="container">
    <div class="container">
      <%= form_with url: publishers_path, method: :get, html: {class: 'm-4 d-flex gap-3' } do |f| %>
        <%= f.text_field :query,
                          class: "form-control",
                          placeholder: 'Search for a Publisher',
                          value: params[:query]
                          %>
        <%= f.submit "Search", class: "btn btn-flat" %>
        <% end %>
    </div>
  </div>
  <table class="border">
    <thead>
      <tr>
        <th>Name</th>
        <th>Amount of Books</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <!-- Insert Publisher data dynamically using your Rails code -->
      <% @publishers.each do |publisher| %>
        <tr>
          <td><%= publisher.name %></td>
          <td><%= link_to publisher.books.count, publisher_path(publisher) %></td>
          <td>
            <%= link_to 'Show', publisher %>
            <%= link_to 'Edit', edit_publisher_path(publisher) %>
            <%= button_to 'Delete', publisher, method: :delete, data: { confirm: 'Are you sure?'} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/publishers/new.html.erb
<div class="container">
  <h1>Create new Publisher</h1>
  <div class="row justify-content-center">
    <div class="col-6 mb-3">
      <%= simple_form_for(@publisher) do |f| %>
        <%= f.input :name %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/publishers/show.html.erb
<div class="container">
  <div class="container-show">
    <h1>Details for Publisher id: <%= @publisher.id %></h1>
    <div class="item-details">
        <p><strong>First Name:</strong> <%= @publisher.name %></p>
        <p><strong>Number of books:</strong> <%= @book_count %></p>
    </div>
    <a class="btn btn-flat" href="<%= publishers_path %>">Back to List</a>
  </div>
</div>
<div class="d-flex flex-wrap gap-4 justify-content-center mb-5">
  <% @publisher.books.each do |book| %>
    <div class="d-flex card text-center col-sm-1 col-md-3">
      <div class="card-header">
        Author: <%= "#{book.author.first_name} #{book.author.last_name}" %>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= book.title %></h5>
        <p class="card-text">Published by: <%= book.publisher.name %></p>
        <p>Price $<%= book.price %></p>
        <% if user_signed_in? %>
          <%= button_to "Add to Favorites", add_to_favorites_book_path(book), method: :post, class: "btn btn-flat", remote: true, data: { confirm: 'Book added to favorites. View your favorites now?' } %>
        <% else %>
          <%= button_to "Log in to add to Favorites", new_user_session_path, class: "btn btn-flat" %>
        <% end %>
      </div>
      <div class="card-footer text-muted d-flex justify-content-center align-items-center">
        Rating: <% book.review.times do %>
          <i class="fa-solid fa-star text-warning"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>