config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :books do
    post 'add_to_favorites', on: :member
    post 'remove_favorites', on: :member
    get 'favorites', on: :collection
  end
  resources :authors
  resources :publishers
  get 'dashboard', to: 'dashboard#dashboard'
  post 'dashboard/update_book_prices', to: 'dashboard#update_book_prices'
  get 'dashboard/books', to: 'dashboard#books'

  namespace :api do
    resources :books, only: %i[index show create update destroy]
  end

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :publisher

  include PgSearch::Model

  pg_search_scope :search_by_title_and_author_and_publisher,
  against: [ :title, :isbn ],
  associated_against: {
    author: [ :first_name, :last_name ],
    publisher: [:name]
  },
  using: {
    tsearch: { prefix: true }
  }

  scope :filter_by_title, ->(title) { where("title ILIKE ?", "%#{title}%") }
  scope :filter_by_author, ->(author_name) { joins(:author).where("authors.first_name ILIKE ? OR authors.last_name ILIKE ?", "%#{author_name}%", "%#{author_name}%") }
  scope :filter_by_price_range, ->(min_price, max_price) { where(price: min_price..max_price) }
  
  acts_as_favoritable
  # Validations
  validates :title, presence: true
  validates :author, presence: true
  validates :date_of_publication, presence: true
  validates :publisher, presence: true
  validates :isbn, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :review, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/controllers/api/books_controller.rb
class Api::BooksController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!
  before_action :set_book, only: %i[ show edit update destroy ]

  def index
    @books = Book.all
    @books = Book.filter_by_title(params[:title]) if params[:title].present?
    @books = Book.filter_by_author(params[:author]) if params[:author].present?
    @books = Book.filter_by_price_range(params[:min_price], params[:max_price]) if params[:min_price].present? && params[:max_price].present?
    @books = @books.page(params[:page]).per(params[:per_page] || 10)
    render json: @books
  end

  def show
    render json: @book
  end

  def create
    @book = Book.new(book_params)
    render json: @book, status: :created
  end

  def update
    @book.update(book_params)
    render json: @book
  end

  def destroy
    @book.destroy
    head :no_content
  end

  private

  def book_params
    params.require(:book).permit(:title, :isbn, :date_of_publication, :review, :price, :author_id, :publisher_id)
  end

  def set_book
    @book = Book.find(params[:id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :add_to_favorites]
  before_action :authorize_admin, except: [:index, :favorites, :add_to_favorites, :remove_favorites ]
  before_action :set_book, only: [:show, :edit, :update, :destroy, :add_to_favorites, :remove_favorites]

  def index
    if params[:query].present?
      @books = Book.search_by_title_and_author_and_publisher(params[:query])
    else
      @books = Book.all
    end
    @books = @books.page(params[:page]).per(10)
    respond_to do |format|
      format.html
      format.text { render partial: 'list', locals: { books: @books }, formats: [:html] }
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.save!
    redirect_to dashboard_books_path
  end

  def show
  end

  def edit
  end

  def update
    @book.update(book_params)
    redirect_to dashboard_books_path
  end

  def destroy
    @book.destroy
    redirect_to dashboard_books_path
  end

  def add_to_favorites
    current_user.favorite(@book) if user_signed_in?
    redirect_to favorites_books_path
  end

  def remove_favorites
    current_user.unfavorite(@book) if user_signed_in?
    redirect_to favorites_books_path
  end

  def favorites
    @favorite_books = current_user.all_favorited
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :isbn, :date_of_publication, :review, :price, :author_id, :publisher_id)
  end
end

app/views/books/_list.html.erb
<div data-search-books-target="list" class="d-flex flex-wrap gap-4 justify-content-center">
  <% books.each do |book| %>
    <div class="d-flex card text-center col-sm-1 col-md-3">
      <div class="card-header">
        Author: <%= "#{book.author.first_name} #{book.author.last_name}" %>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= book.title %></h5>
        <p class="card-text">Published by: <%= book.publisher.name %></p>
        <p>Price $<%= book.price %></p>
        <% if user_signed_in? %>
          <%= button_to "Add to Favorites", add_to_favorites_book_path(book), method: :post, class: "btn btn-flat", remote: true, data: { confirm: 'Book added to favorites. View your favorites now?' } %>
        <% else %>
          <%= button_to "Log in to add to Favorites", new_user_session_path, class: "btn btn-flat" %>
        <% end %>
      </div>
      <div class="card-footer text-muted d-flex justify-content-center align-items-center">
        Rating: <% book.review.times do %>
          <i class="fa-solid fa-star text-warning"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
  <h3>Edit <%= @book.title %></h3>
  <div class="row justify-content-center">
    <div class="col-6">
      <%= simple_form_for(@book) do |f| %>
        <%= f.input :title %>
        <%= f.input :isbn %>
        <%= f.input :date_of_publication %>
        <%= f.input :review %>
        <%= f.input :price %>
        <%= f.submit %>
      <% end %>
      <%= link_to "Delete", dashboard_books_path(@book), method: :destroy, data: { turbo_confirm: "Are you sure you want to remove this book?" }, class: 'text-danger' %>
    </div>
  </div>
</div>

app/views/books/favorites.html.erb
<div data-search-books-target="list" class="d-flex flex-wrap gap-4 justify-content-center mt-4">
  <% @favorite_books.each do |book| %>
    <div class="d-flex card text-center col-sm-1 col-md-3">
      <div class="card-header">
        Author: <%= "#{book.author.first_name} #{book.author.last_name}" %>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= book.title %></h5>
        <p class="card-text">Published by:<%= book.publisher.name %></p>
          <%= button_to "Remove from Favorites", remove_favorites_book_path(book), method: :post, class: "btn btn-danger", remote: true %>
      </div>
      <div class="card-footer text-muted d-flex justify-content-center align-items-center">
        Rating: <% book.review.times do %>
          <i class="fa-solid fa-star text-warning"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div class="container d-flex justify-content-center mt-5">
  <%= link_to "Back to All Books", books_path, class: "btn btn-flat" %>
</div>

app/views/books/index.html.erb
<div class="container" data-controller="search-books">
  <div class="container">
    <%= form_with url: books_path, method: :get, html: {class: 'mb-4', data: {search_books_target: "form"}} do |f| %>
      <%= f.text_field :query,
                        class: "form-control",
                        placeholder: 'Type a Book title',
                        value: params[:query],
                        data: {
                          search_books_target: "input",
                          action: "keyup->search-books#search"
                          }
                        %>
      <% end %>
  </div>
  <%= render 'list', books: @books %>
</div>
<div class="pagination justify-content-center m-4">
  <%= paginate @books %>
</div>

app/views/books/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6 mb-3">
      <%= simple_form_for(@book) do |f| %>
        <%= f.input :title %>
        <%= f.input :isbn %>
        <%= f.input :date_of_publication %>
        <%= f.input :review %>
        <%= f.input :price %>
        <%= f.input :publisher_id %>
        <%= f.input :author_id %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="container-show">
    <h1>Details for Book id: <%= @book.id %></h1>
    <div class="item-details">
        <p><strong>Title:</strong> <%= @book.title %></p>
        <p><strong>ISBN:</strong> <%= @book.isbn %></p>
        <p><strong>Date of Publication:</strong> <%= @book.date_of_publication %></p>
        <p><strong>Review:</strong> <%= @book.review %></p>
        <p><strong>Price:</strong> <%= @book.price %></p>
    </div>
    <a class="btn btn-flat" href="<%= dashboard_books_path %>">Back to List</a>
  </div>
</div>